### ISSUE TITLE
Crear tabla de contenido explicando todo en 4Geeks

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#5568]
Para cada uno de los siguientes puntos, debes crear un articulo que funcione para explicar a los usuarios como funciona 4Geeks, utiliza chatGPT para apoyarte en la creacion de cada articulo, tiene que ser muy amigable y utilizar imagenes, GIF o videos, para poder explicar cada uno de los procesos.

- [x] IntroductionAbout 4Geeks
- [x] Getting Started with 4Geeks
- [x] Account Management
- [ ] Creating an Account
- [ ] Managing Your Account
- [x] Learning with 4Geeks
- [x] Course Structure
- [ ] Videos
- [ ] Text-based Lessons
- [ ] Interactive Lessons
- [ ] Searching for Courses
- [ ] Enrolling in a Course
- [ ] Course Progress and Completion
- [ ] 1-1 On Demand MentoringScheduling a Session
- [ ] Preparing for a Session
- [ ] During a Session
- [ ] After a Session
- [ ] WorkshopsFinding and Enrolling in Workshops
- [ ] Participating in Workshops
- [ ] After the Workshop
- [ ] Code Review and AssessmentsSubmitting your Code for Review
- [ ] Understanding the Code Review Feedback
- [ ] Revisions and Resubmissions
- [ ] Interactive and Autograded TutorialsGetting Started with Tutorials
- [ ] Tutorial Progress and Scoring
- [ ] User GuidesUsing the Platform (general)
- [ ] Using the Course Dashboard
- [ ] Using the Workshop Dashboard
- [ ] Using the Mentoring Dashboard
- [ ] TroubleshootingCommon Problems and Solutions
- [ ] Contacting Support
- [ ] Security Measures

**Comment by Lorenagubaira** [comment]
- [x] IntroductionAbout 4Geeks
- [x] Getting Started with 4Geeks
- [x] Account Management
- [x] Creating an Account
- [x] Managing Your Account
- [x] Learning with 4Geeks
- [x] Course Structure
- [x] Videos
- [x] Text-based Lessons
- [x] Interactive Lessons
- [x] Searching for Courses
- [ ] Enrolling in a Course
- [x] Course Progress and Completion
- [x] 1-1 On Demand MentoringScheduling a Session
- [x] Preparing for a Session
- [x] During a Session
- [x] After a Session
- [x] WorkshopsFinding and Enrolling in Workshops
- [x] Participating in Workshops
- [x] After the Workshop
- [x] Code Review and AssessmentsSubmitting your Code for Review
- [ ] Understanding the Code Review Feedback
- [ ] Revisions and Resubmissions
- [x] Interactive and Autograded TutorialsGetting Started with Tutorials
- [x] Tutorial Progress and Scoring
- [x] User GuidesUsing the Platform (general)
- [ ] Using the Course Dashboard
- [ ] Using the Workshop Dashboard
- [ ] Using the Mentoring Dashboard
- [ ] TroubleshootingCommon Problems and Solutions
- [ ] Contacting Support
- [ ] Security Measure
