### ISSUE TITLE
Regenerar meta-descriptions de todas las lessons

### ISSUE THREAD

**Issue by alesanchezr** [breatheco-de/breatheco-de#6831]
- [ ] Create an action `generates_asset_metadescription` based on its SEO keyword and the article content.
- [ ] Use Rigobot API for the AI generation; the completion template is `seo-article-meta-mescription`, here is the API documentation for [creating a completion job](https://documenter.getpostman.com/view/2432393/2s93sZ6Duq#e72a5f0a-d427-4500-81ff-6077db7b0823).
- [ ] If the article is empty or there is not SEO keyword, the action must raise an error and log the error into the asset [with this log_error function](https://github.com/breatheco-de/apiv2/blob/a6f531b767aed73fa1ee9cbd1966fe09eb01677f/breathecode/registry/models.py#L635), that way it will be followed up by the content team.
- [ ] Create a django command to go over all the assets without descriptions that are `asset.is_seo_tracked=true` and also have a SEO keyword associated and uses the `generates_asset_metadescription` action to asynchronously task to create the descriptions for the articles.

---
**Source URL**:
[https://app.ahrefs.com/site-audit/3643119/121/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2CmetaDescription%2CmetaDescriptionLength%2CnrMetaDescription%2Ccompliant&filterId=9edec11a67a2ebde68902cbf437af7b4&issueId=c64d5156-d0f4-11e7-8ed1-001e67ed4656](https://app.ahrefs.com/site-audit/3643119/121/data-explorer?columns=pageRating%2Curl%2Ctraffic%2ChttpCode%2Cdepth%2CmetaDescription%2CmetaDescriptionLength%2CnrMetaDescription%2Ccompliant&filterId=9edec11a67a2ebde68902cbf437af7b4&issueId=c64d5156-d0f4-11e7-8ed1-001e67ed4656)
