### ISSUE TITLE
Add modal when you have pending subtasks before moving to another lesson

### ISSUE THREAD

**Issue by tommygonzaleza** [breatheco-de/breatheco-de#7928]
Here is the design: https://www.figma.com/design/hJsE2D6fu3peR49mt6kZD1/4Geeks.com?node-id=2256-102586&t=umpfEs3m6ztcjBQM-1. We are going to reuse the component that shows how many subtask you've completed

**Comment by KonnorThatcher** [comment]
- [ ] When I click on Take me there in the modal it should remove the modal and take me to the first uncompleted subtask

The "Take me there" button still doesn't close the modal nor does it scroll the screen to the first unchecked subtask.
https://www.loom.com/share/2cdb0136063a49b7b5b98c80cf4de080?sid=4afee0cb-e0e3-4da9-b994-3c10b205a310

**Comment by tommygonzaleza** [comment]
- [ ] Add fields `position` and `lang` in the subtask json object.
- [ ] When changing to the other asset's language, mark the tasks as completed in the order they are in the other lang.
- [ ] Change the message of the modal to the one of figma.
- [ ] Use a short hash as the id which should be the label of the checkbox, converted into hash
